### ISSUE TITLE
The "Known issues" section is very useful, but a bit misleading

### ISSUE THREAD

**Issue by Dmitriusan** [ellaqezi/dotfiles#1]
The "Known issues" section https://github.com/ellaqezi/dotfiles#known-issues says
```
bug BUG filetree affects version 2.4 warning 
throws error: 'dict object' has no attribute 'src' although the dictionary starts with (item={'src': 

unicorn FIX concatenate item.root and item.path and use that instead of item.src
```

I faced the same issue, and your "Known issues" section gave me a hint (Thanks!). Later I've finally found this answer https://github.com/ansible/ansible/issues/51513#issuecomment-459150769 that explains the reasoning.

Also created PR with documentation update https://github.com/ansible/ansible/pull/54347

Just FYI

**Comment by ellaqezi** [comment]
thanks for mentioning me on your PR, I'll remove the section from the readme.
